disabled_rules: # rule identifiers to exclude from running
  - line_length
  - shorthand_operator
  - trailing_whitespace

opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_failure_calls
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optiona
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_arrow_whitespace
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

custom_rules:
  explicit_failure_calls:
    name: "Avoid asserting 'false'"
    regex: '((assert|precondition)\(false)'
    message: "Use assertionFailure() or preconditionFailure() instead."
    severity: warning

trailing_semicolon: warning

no_extension_access_modifier:
  severity: warning
  
class_delegate_protocol:
  severity: warning

closure_parameter_position:
  severity: warning

colon:
  severity: warning

comma:
  severity: warning

control_statement:
  severity: warning

discouraged_direct_init:
  severity: warning

empty_enum_arguments:
  severity: warning

empty_parentheses_with_trailing_closure:
  severity: warning

for_where:
  severity: warning

implicit_getter:
  severity: warning

legacy_constructor:
  severity: warning

mark:
  severity: warning

multiple_closures_with_trailing_closure:
  severity: warning

notification_center_detachment:
  severity: warning

opening_brace:
  severity: warning

private_over_fileprivate:
  severity: warning

redundant_discardable_let:
  severity: warning

redundant_optional_initialization:
  severity: warning

redundant_void_return:
  severity: warning

syntactic_sugar:
  severity: warning

todo:
  severity: warning

trailing_newline:
  severity: warning

unneeded_break_in_switch:
  severity: warning

unused_closure_parameter:
  severity: warning

unused_optional_binding:
  severity: warning

vertical_parameter_alignment:
  severity: warning

void_return:
  severity: warning

weak_delegate:
  severity: warning

xctfail_message:
  severity: warning

function_parameter_count:
  warning: 11
  error: 15

type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 80
  
file_length: 
  error: 1000
  warning: 400

cyclomatic_complexity:
  warning: 10

function_body_length:
  warning: 40


type_body_length:
  warning: 200

nesting:
  type_level:
    warning: 3
    error: 4
  statement_level:
    warning: 4
    error: 6

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 60
    error: 100
  excluded:
    - id
